import { Level } from '../types/game';
import { GAME_CONFIG } from './game';

const { GRID_SIZE } = GAME_CONFIG;

// Helper to create empty layout
const createEmptyLayout = (): number[][] => {
  return Array(GRID_SIZE).fill(0).map(() => Array(GRID_SIZE).fill(0));
};

// Helper to create wall layout
const createWallLayout = (): number[][] => {
  const layout = createEmptyLayout();
  // Add some walls (1 = block)
  for (let i = 2; i < GRID_SIZE - 2; i++) {
    layout[i][3] = 1;
    layout[i][4] = 1;
  }
  return layout;
};

// Helper to create corners layout
const createCornersLayout = (): number[][] => {
  const layout = createEmptyLayout();
  layout[0][0] = 1;
  layout[0][GRID_SIZE - 1] = 1;
  layout[GRID_SIZE - 1][0] = 1;
  layout[GRID_SIZE - 1][GRID_SIZE - 1] = 1;
  return layout;
};

export const LEVELS: Level[] = [
  {
    id: 1,
    name: 'キャンディ平原',
    description: '基本ステージ。目標スコアを達成してみよう。',
    targetScore: 800,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage1.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 2,
    name: 'シュガー洞窟',
    description: '壁が邪魔をしているぞ。隣で消して壊そう！',
    targetScore: 1400,
    moveLimit: 26,
    pieceTypes: 9,
    background: 'bg_stage2.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 3,
    name: 'キャラメル崖',
    description: '四隅が埋まっている。中央でコンボを狙え！',
    targetScore: 2000,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage3.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 4,
    name: 'Stage 4',
    description: 'どんどん難しくなるぞ！',
    targetScore: 2800,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage4.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 5,
    name: 'Stage 5',
    description: 'どんどん難しくなるぞ！',
    targetScore: 3600,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage5.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 6,
    name: 'Stage 6',
    description: 'どんどん難しくなるぞ！',
    targetScore: 4400,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage6.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 7,
    name: 'Stage 7',
    description: 'どんどん難しくなるぞ！',
    targetScore: 5200,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage7.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 8,
    name: 'Stage 8',
    description: 'どんどん難しくなるぞ！',
    targetScore: 6000,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage8.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 9,
    name: 'Stage 9',
    description: 'どんどん難しくなるぞ！',
    targetScore: 6800,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage9.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 10,
    name: 'Stage 10',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 7600,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage10.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 11,
    name: 'Stage 11',
    description: 'どんどん難しくなるぞ！',
    targetScore: 8400,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage11.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 12,
    name: 'Stage 12',
    description: 'どんどん難しくなるぞ！',
    targetScore: 9200,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage12.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 13,
    name: 'Stage 13',
    description: 'どんどん難しくなるぞ！',
    targetScore: 10000,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage13.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 14,
    name: 'Stage 14',
    description: 'どんどん難しくなるぞ！',
    targetScore: 10800,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage14.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 15,
    name: 'Stage 15',
    description: 'どんどん難しくなるぞ！',
    targetScore: 11600,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage15.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 16,
    name: 'Stage 16',
    description: 'どんどん難しくなるぞ！',
    targetScore: 12400,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage16.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 17,
    name: 'Stage 17',
    description: 'どんどん難しくなるぞ！',
    targetScore: 13200,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage17.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 18,
    name: 'Stage 18',
    description: 'どんどん難しくなるぞ！',
    targetScore: 14000,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage18.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 19,
    name: 'Stage 19',
    description: 'どんどん難しくなるぞ！',
    targetScore: 14800,
    moveLimit: 24,
    pieceTypes: 9,
    background: 'bg_stage19.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 20,
    name: 'Stage 20',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 15600,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage20.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 21,
    name: 'Stage 21',
    description: 'どんどん難しくなるぞ！',
    targetScore: 16400,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage21.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 22,
    name: 'Stage 22',
    description: 'どんどん難しくなるぞ！',
    targetScore: 17200,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage22.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 23,
    name: 'Stage 23',
    description: 'どんどん難しくなるぞ！',
    targetScore: 18000,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage23.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 24,
    name: 'Stage 24',
    description: 'どんどん難しくなるぞ！',
    targetScore: 18800,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage24.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 25,
    name: 'Stage 25',
    description: 'どんどん難しくなるぞ！',
    targetScore: 19600,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage25.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 26,
    name: 'Stage 26',
    description: 'どんどん難しくなるぞ！',
    targetScore: 20400,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage26.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 27,
    name: 'Stage 27',
    description: 'どんどん難しくなるぞ！',
    targetScore: 21200,
    moveLimit: 23,
    pieceTypes: 9,
    background: 'bg_stage27.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 28,
    name: 'Stage 28',
    description: 'どんどん難しくなるぞ！',
    targetScore: 22000,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage28.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 29,
    name: 'Stage 29',
    description: 'どんどん難しくなるぞ！',
    targetScore: 22800,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage29.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 30,
    name: 'Stage 30',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 23600,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage30.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 31,
    name: 'Stage 31',
    description: 'どんどん難しくなるぞ！',
    targetScore: 24400,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage31.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 32,
    name: 'Stage 32',
    description: 'どんどん難しくなるぞ！',
    targetScore: 25200,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage32.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 33,
    name: 'Stage 33',
    description: 'どんどん難しくなるぞ！',
    targetScore: 26000,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage33.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 34,
    name: 'Stage 34',
    description: 'どんどん難しくなるぞ！',
    targetScore: 26800,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage34.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 35,
    name: 'Stage 35',
    description: 'どんどん難しくなるぞ！',
    targetScore: 27600,
    moveLimit: 22,
    pieceTypes: 9,
    background: 'bg_stage35.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 36,
    name: 'Stage 36',
    description: 'どんどん難しくなるぞ！',
    targetScore: 28400,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage36.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 37,
    name: 'Stage 37',
    description: 'どんどん難しくなるぞ！',
    targetScore: 29200,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage37.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 38,
    name: 'Stage 38',
    description: 'どんどん難しくなるぞ！',
    targetScore: 30000,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage38.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 39,
    name: 'Stage 39',
    description: 'どんどん難しくなるぞ！',
    targetScore: 30800,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage39.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 40,
    name: 'Stage 40',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 31600,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage40.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 41,
    name: 'Stage 41',
    description: 'どんどん難しくなるぞ！',
    targetScore: 32400,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage41.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 42,
    name: 'Stage 42',
    description: 'どんどん難しくなるぞ！',
    targetScore: 33200,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage42.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 43,
    name: 'Stage 43',
    description: 'どんどん難しくなるぞ！',
    targetScore: 34000,
    moveLimit: 21,
    pieceTypes: 9,
    background: 'bg_stage43.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 44,
    name: 'Stage 44',
    description: 'どんどん難しくなるぞ！',
    targetScore: 34800,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage44.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 45,
    name: 'Stage 45',
    description: 'どんどん難しくなるぞ！',
    targetScore: 35600,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage45.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 46,
    name: 'Stage 46',
    description: 'どんどん難しくなるぞ！',
    targetScore: 36400,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage46.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 47,
    name: 'Stage 47',
    description: 'どんどん難しくなるぞ！',
    targetScore: 37200,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage47.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 48,
    name: 'Stage 48',
    description: 'どんどん難しくなるぞ！',
    targetScore: 38000,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage48.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 49,
    name: 'Stage 49',
    description: 'どんどん難しくなるぞ！',
    targetScore: 38800,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage49.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 50,
    name: 'Stage 50',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 39600,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage50.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 51,
    name: 'Stage 51',
    description: 'どんどん難しくなるぞ！',
    targetScore: 40400,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage51.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 52,
    name: 'Stage 52',
    description: 'どんどん難しくなるぞ！',
    targetScore: 41200,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage52.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 53,
    name: 'Stage 53',
    description: 'どんどん難しくなるぞ！',
    targetScore: 42000,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage53.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 54,
    name: 'Stage 54',
    description: 'どんどん難しくなるぞ！',
    targetScore: 42800,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage54.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 55,
    name: 'Stage 55',
    description: 'どんどん難しくなるぞ！',
    targetScore: 43600,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage55.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 56,
    name: 'Stage 56',
    description: 'どんどん難しくなるぞ！',
    targetScore: 44400,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage56.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 57,
    name: 'Stage 57',
    description: 'どんどん難しくなるぞ！',
    targetScore: 45200,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage57.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 58,
    name: 'Stage 58',
    description: 'どんどん難しくなるぞ！',
    targetScore: 46000,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage58.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 59,
    name: 'Stage 59',
    description: 'どんどん難しくなるぞ！',
    targetScore: 46800,
    moveLimit: 19,
    pieceTypes: 9,
    background: 'bg_stage59.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 60,
    name: 'Stage 60',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 47600,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage60.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 61,
    name: 'Stage 61',
    description: 'どんどん難しくなるぞ！',
    targetScore: 48400,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage61.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 62,
    name: 'Stage 62',
    description: 'どんどん難しくなるぞ！',
    targetScore: 49200,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage62.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 63,
    name: 'Stage 63',
    description: 'どんどん難しくなるぞ！',
    targetScore: 50000,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage63.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 64,
    name: 'Stage 64',
    description: 'どんどん難しくなるぞ！',
    targetScore: 50800,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage64.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 65,
    name: 'Stage 65',
    description: 'どんどん難しくなるぞ！',
    targetScore: 51600,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage65.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 66,
    name: 'Stage 66',
    description: 'どんどん難しくなるぞ！',
    targetScore: 52400,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage66.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 67,
    name: 'Stage 67',
    description: 'どんどん難しくなるぞ！',
    targetScore: 53200,
    moveLimit: 18,
    pieceTypes: 9,
    background: 'bg_stage67.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 68,
    name: 'Stage 68',
    description: 'どんどん難しくなるぞ！',
    targetScore: 54000,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage68.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 69,
    name: 'Stage 69',
    description: 'どんどん難しくなるぞ！',
    targetScore: 54800,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage69.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 70,
    name: 'Stage 70',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 55600,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage70.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 71,
    name: 'Stage 71',
    description: 'どんどん難しくなるぞ！',
    targetScore: 56400,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage71.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 72,
    name: 'Stage 72',
    description: 'どんどん難しくなるぞ！',
    targetScore: 57200,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage72.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 73,
    name: 'Stage 73',
    description: 'どんどん難しくなるぞ！',
    targetScore: 58000,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage73.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 74,
    name: 'Stage 74',
    description: 'どんどん難しくなるぞ！',
    targetScore: 58800,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage74.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 75,
    name: 'Stage 75',
    description: 'どんどん難しくなるぞ！',
    targetScore: 59600,
    moveLimit: 17,
    pieceTypes: 9,
    background: 'bg_stage75.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 76,
    name: 'Stage 76',
    description: 'どんどん難しくなるぞ！',
    targetScore: 60400,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage76.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 77,
    name: 'Stage 77',
    description: 'どんどん難しくなるぞ！',
    targetScore: 61200,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage77.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 78,
    name: 'Stage 78',
    description: 'どんどん難しくなるぞ！',
    targetScore: 62000,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage78.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 79,
    name: 'Stage 79',
    description: 'どんどん難しくなるぞ！',
    targetScore: 62800,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage79.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 80,
    name: 'Stage 80',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 63600,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage80.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 81,
    name: 'Stage 81',
    description: 'どんどん難しくなるぞ！',
    targetScore: 64400,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage81.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 82,
    name: 'Stage 82',
    description: 'どんどん難しくなるぞ！',
    targetScore: 65200,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage82.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 83,
    name: 'Stage 83',
    description: 'どんどん難しくなるぞ！',
    targetScore: 66000,
    moveLimit: 16,
    pieceTypes: 9,
    background: 'bg_stage83.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 84,
    name: 'Stage 84',
    description: 'どんどん難しくなるぞ！',
    targetScore: 66800,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage84.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 85,
    name: 'Stage 85',
    description: 'どんどん難しくなるぞ！',
    targetScore: 67600,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage85.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 86,
    name: 'Stage 86',
    description: 'どんどん難しくなるぞ！',
    targetScore: 68400,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage86.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 87,
    name: 'Stage 87',
    description: 'どんどん難しくなるぞ！',
    targetScore: 69200,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage87.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 88,
    name: 'Stage 88',
    description: 'どんどん難しくなるぞ！',
    targetScore: 70000,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage88.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 89,
    name: 'Stage 89',
    description: 'どんどん難しくなるぞ！',
    targetScore: 70800,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage89.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 90,
    name: 'Stage 90',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 71600,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage90.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 91,
    name: 'Stage 91',
    description: 'どんどん難しくなるぞ！',
    targetScore: 72400,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage91.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 92,
    name: 'Stage 92',
    description: 'どんどん難しくなるぞ！',
    targetScore: 73200,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage92.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 93,
    name: 'Stage 93',
    description: 'どんどん難しくなるぞ！',
    targetScore: 74000,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage93.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 94,
    name: 'Stage 94',
    description: 'どんどん難しくなるぞ！',
    targetScore: 74800,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage94.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 95,
    name: 'Stage 95',
    description: 'どんどん難しくなるぞ！',
    targetScore: 75600,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage95.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 96,
    name: 'Stage 96',
    description: 'どんどん難しくなるぞ！',
    targetScore: 76400,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage96.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 97,
    name: 'Stage 97',
    description: 'どんどん難しくなるぞ！',
    targetScore: 77200,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage97.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 98,
    name: 'Stage 98',
    description: 'どんどん難しくなるぞ！',
    targetScore: 78000,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage98.png',
    bgm: 'bgm_stage1.mp3',
    layout: createWallLayout(),
  },
  {
    id: 99,
    name: 'Stage 99',
    description: 'どんどん難しくなるぞ！',
    targetScore: 78800,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage99.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 100,
    name: 'Stage 100',
    description: 'ボス級の難易度だ！慎重にいこう。',
    targetScore: 79600,
    moveLimit: 15,
    pieceTypes: 9,
    background: 'bg_stage100.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
];
