import { Level } from '../types/game';
import { GAME_CONFIG } from './game';

const { GRID_SIZE } = GAME_CONFIG;

// Helper to create empty layout
const createEmptyLayout = (): number[][] => {
  return Array(GRID_SIZE).fill(0).map(() => Array(GRID_SIZE).fill(0));
};

// Helper to create wall layout
const createWallLayout = (): number[][] => {
  const layout = createEmptyLayout();
  // Add some walls (1 = block)
  for (let i = 2; i < GRID_SIZE - 2; i++) {
    layout[i][3] = 1;
    layout[i][4] = 1;
  }
  return layout;
};

// Helper to create corners layout
const createCornersLayout = (): number[][] => {
  const layout = createEmptyLayout();
  layout[0][0] = 1;
  layout[0][GRID_SIZE - 1] = 1;
  layout[GRID_SIZE - 1][0] = 1;
  layout[GRID_SIZE - 1][GRID_SIZE - 1] = 1;
  return layout;
};

export const LEVELS: Level[] = [
  {
    id: 1,
    name: 'TAMAGO',
    description: '基本ステージ。目標スコアを達成してみよう。',
    targetScore: 1000,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage1.png',
    bgm: 'bgm_stage1.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 2,
    name: 'SHAKE',
    description: '壁が邪魔をしているぞ。隣で消して壊そう!',
    targetScore: 1100,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage2.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 3,
    name: 'UME',
    description: '四隅が埋まっている。中央でコンボを狙え!',
    targetScore: 1100,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage3.png',
    bgm: 'bgm_stage3.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 4,
    name: 'OKAKA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1100,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage4.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 5,
    name: 'KONBU',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1200,
    moveLimit: 20,
    pieceTypes: 9,
    background: 'bg_stage5.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 6,
    name: 'TARAKO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1500,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage6.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 7,
    name: 'TSUNA MAYO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1500,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage7.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 8,
    name: 'IKURA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1600,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage8.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 9,
    name: 'MENTAIKO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1600,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage9.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 10,
    name: 'NEGITORO',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 2000,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage10.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 11,
    name: 'EBIMAYON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1700,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage11.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 12,
    name: 'KARAAGE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1700,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage12.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 13,
    name: 'NIKU MISO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1700,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage13.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 14,
    name: 'TENMUSU',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1800,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage14.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 15,
    name: 'TAKANA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1800,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage15.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 16,
    name: 'WAKAME',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1900,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage16.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 17,
    name: 'SAKE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1900,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage17.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 18,
    name: 'SHIO MUSUBI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 1900,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage18.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 19,
    name: 'YUKARI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2000,
    moveLimit: 25,
    pieceTypes: 9,
    background: 'bg_stage19.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 20,
    name: 'KATSUOBUSHI',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 2400,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage20.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 21,
    name: 'NORI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2400,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage21.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 22,
    name: 'SHISO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2500,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage22.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 23,
    name: 'GOMA SHIO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2500,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage23.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 24,
    name: 'KIMCHI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2600,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage24.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 25,
    name: 'YAKI ONIGIRI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2600,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage25.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 26,
    name: 'TOFU',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2700,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage26.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 27,
    name: 'NATTO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2700,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage27.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 28,
    name: 'MISO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2800,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage28.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 29,
    name: 'SHOYU',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2800,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage29.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 30,
    name: 'WASABI',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 3300,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage30.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 31,
    name: 'GINGER',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2900,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage31.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 32,
    name: 'KARASHI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 2900,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage32.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 33,
    name: 'DAIKON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3000,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage33.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 34,
    name: 'CARROT',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3000,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage34.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 35,
    name: 'TOMATO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3100,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage35.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 36,
    name: 'CUCUMBER',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3100,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage36.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 37,
    name: 'LETTUCE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3200,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage37.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 38,
    name: 'CABBAGE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3200,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage38.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 39,
    name: 'SPINACH',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3300,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage39.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 40,
    name: 'BROCCOLI',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 3900,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage40.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 41,
    name: 'CORN',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3300,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage41.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 42,
    name: 'POTATO',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3400,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage42.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 43,
    name: 'PUMPKIN',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3400,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage43.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 44,
    name: 'EGGPLANT',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3500,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage44.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 45,
    name: 'MUSHROOM',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3500,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage45.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 46,
    name: 'SHIITAKE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3600,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage46.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 47,
    name: 'ENOKI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3600,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage47.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 48,
    name: 'ONION',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3700,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage48.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 49,
    name: 'GARLIC',
    description: 'どんどん難しくなるぞ!',
    targetScore: 3700,
    moveLimit: 30,
    pieceTypes: 9,
    background: 'bg_stage49.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 50,
    name: 'LEEK',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 4400,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage50.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 51,
    name: 'APPLE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4400,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage51.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 52,
    name: 'BANANA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4500,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage52.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 53,
    name: 'ORANGE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4500,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage53.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 54,
    name: 'STRAWBERRY',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4600,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage54.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 55,
    name: 'MELON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4600,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage55.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 56,
    name: 'WATERMELON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4700,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage56.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 57,
    name: 'GRAPE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4700,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage57.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 58,
    name: 'PEACH',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4800,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage58.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 59,
    name: 'PEAR',
    description: 'どんどん難しくなるぞ!',
    targetScore: 4800,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage59.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 60,
    name: 'MANGO',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 5600,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage60.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 61,
    name: 'KIWI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5000,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage61.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 62,
    name: 'PINEAPPLE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5000,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage62.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 63,
    name: 'LEMON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5100,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage63.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 64,
    name: 'CHERRY',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5100,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage64.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 65,
    name: 'CHICKEN',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5200,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage65.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 66,
    name: 'BEEF',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5200,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage66.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 67,
    name: 'PORK',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5300,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage67.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 68,
    name: 'BACON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5300,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage68.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 69,
    name: 'SAUSAGE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5400,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage69.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 70,
    name: 'CHEESE',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 6200,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage70.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 71,
    name: 'BUTTER',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5500,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage71.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 72,
    name: 'YOGURT',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5500,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage72.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 73,
    name: 'MILK',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5600,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage73.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 74,
    name: 'CREAM',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5600,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage74.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 75,
    name: 'BREAD',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5700,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage75.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 76,
    name: 'RICE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5700,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage76.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 77,
    name: 'PASTA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5800,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage77.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 78,
    name: 'NOODLE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5800,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage78.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 79,
    name: 'UDON',
    description: 'どんどん難しくなるぞ!',
    targetScore: 5900,
    moveLimit: 35,
    pieceTypes: 9,
    background: 'bg_stage79.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 80,
    name: 'SOBA',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 6800,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage80.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 81,
    name: 'RAMEN',
    description: 'どんどん難しくなるぞ!',
    targetScore: 6900,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage81.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 82,
    name: 'SUSHI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 6900,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage82.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 83,
    name: 'SASHIMI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7000,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage83.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 84,
    name: 'TEMPURA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7000,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage84.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 85,
    name: 'YAKITORI',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7100,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage85.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 86,
    name: 'TONKATSU',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7200,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage86.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 87,
    name: 'GYOZA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7200,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage87.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 88,
    name: 'CURRY',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7300,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage88.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 89,
    name: 'STEW',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7300,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage89.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 90,
    name: 'SOUP',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 8300,
    moveLimit: 45,
    pieceTypes: 9,
    background: 'bg_stage90.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 91,
    name: 'SALAD',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7500,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage91.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 92,
    name: 'SANDWICH',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7500,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage92.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 93,
    name: 'PIZZA',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7600,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage93.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 94,
    name: 'HAMBURGER',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7600,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage94.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 95,
    name: 'STEAK',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7700,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage95.png',
    bgm: 'bgm_stage5.mp3',
    layout: createWallLayout(),
  },
  {
    id: 96,
    name: 'CHOCOLATE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7800,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage96.png',
    bgm: 'bgm_stage6.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 97,
    name: 'COOKIE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7800,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage97.png',
    bgm: 'bgm_stage1.mp3',
    layout: createCornersLayout(),
  },
  {
    id: 98,
    name: 'CAKE',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7900,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage98.png',
    bgm: 'bgm_stage2.mp3',
    layout: createWallLayout(),
  },
  {
    id: 99,
    name: 'PUDDING',
    description: 'どんどん難しくなるぞ!',
    targetScore: 7900,
    moveLimit: 40,
    pieceTypes: 9,
    background: 'bg_stage99.png',
    bgm: 'bgm_stage3.mp3',
    layout: createEmptyLayout(),
  },
  {
    id: 100,
    name: 'ICE CREAM',
    description: 'ボス級の難易度だ!慎重にいこう。',
    targetScore: 9000,
    moveLimit: 45,
    pieceTypes: 9,
    background: 'bg_stage100.png',
    bgm: 'bgm_stage4.mp3',
    layout: createCornersLayout(),
  },
];
